security:
    encoders:
        App\Entity\User:
            algorithm: auto

    enable_authenticator_manager: false
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        refresh:
            pattern: ^/api/token/refresh
            stateless: true
            anonymous: true
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/api
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            http_basic: ~
            switch_user: true
            anonymous: lazy
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: frontend_home
                # where to redirect after logout
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

        #main:
            #anonymous: true
            #lazy: true
            #provider: app_user_provider
            #custom_authenticator: App\Security\LoginFormAuthenticator
            #logout:
                #path: app_logout
                # where to redirect after logout
                # target: app_any_route
            #remember_me:
                #secret: '%kernel.secret%'
                #lifetime: 604800 # 1 week in seconds
                #path: /
                #always_remember_me: true
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/api, roles: IS_AUTHENTICATED_FULLY } # A DECOMMENTEZ EN PROD POUR AUTHENTIFICATION JWT
        #- { path: ^/profile, roles: ROLE_USER }
